version: "3.8"
services:
  bancodados:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=value
    ports: 
      - 2020:5432
    networks:
      - aplicacao

  aplicacaocaptura:
    image: danielly/captura:latest
    environment:
      - DATABASE_URL=postgresql://postgres:value@bancodados:5432/captura?schema=public
    ports: 
      - 3333:3333 
    networks:
      - aplicacao
networks:
  aplicacao:
